### ISSUE TITLE
Discussion Exercise 1: <Traversing the Tree/> reading

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#98] opened 2016-01-07 22:20 UTC
### The reading: Gabrielle Kirilloff, “[&lt;Traversing_the_Tree/&gt;](http://gk.obdurodon.org/seminar/seminarPaper.xhtml)”,
*Special note of interest:* Gabi Kirilloff was a student in [a digital humanities course at Pitt like the one you are taking](http://dh.obdurodon.org), and she originally wrote &lt;Traversing_the_Tree/&gt; for a seminar paper assignment in another class. 

### The discussion prompts:
* What perspective does Kirilloff provide on the kinds of XML markup we are learning, the history and context of hierarchical markup, and its potential issues? 
* "OCHO" stands for Ordered Hierarchy of Content Objects, and it's the subject of much of Kirilloff's essay. What's so important and/or problematic about OHCO? Is OHCO a bad thing? Or actually not? 
* Consider the examples of **overlapping hierarchies** that Kirilloff presents: Which of these did you find especially interesting?
* Think about the problems posted by overlapping hierarchies. What ideas are presented for how to deal with these in code, and how effective might these be?  Is it possible to write XML to get around the problems raised in this piece?

The discussion is worth points to you as a homework exercise. For full credit, your posts should make specific reference to passages in Kirilloff's essay, and reflect on those passages. **Note:** You (as an individual) do not have to respond to every one of the discussion prompts, but the class as a whole should cover them all. (A good goal for each of you is to try to address two of the above prompts in some way in your posts.) Raising questions is encouraged, and so is responding to each other, but responding should do more than simply say, "yes, I agree." A good response will add something new to the conversation, or help promote more discussion. You should make **at least two substantial posts** to fully contribute to the discussion.

As you're drafting your comments, **see if you can apply "Markdown" formatting** if you'd like to use bold or italics or make a list, form a link, add an image, etc. Follow the link to "Markdown supported" at the top right of the comment "Write" screen for an orientation to Github's markdown.

**Comment by nlottig94** [comment] 2016-01-10 04:12
Okay, so we know what OHCO stands for, which Kirilloff discusses [here](http://gk.obdurodon.org/seminar/seminarPaper.xhtml#P5), but what is the importance and the problems of it?  Well, for starters, the importance of OHCO is that it helps digital humanists (AKA: us!) encode a multitude of texts that are presented to us in an organized manner.  OHCO helps to keep all the digital, encoded work of all digital humanists looking and organized in a certain way, so that it is decently human readable.  For example, we can compare these two XML markups from last semesters digital humanities projects: [Emily Dickinson: Fascicle 16](http://dickinson16.newtfire.org/xml/1601variant.xml) and [The Restoration of Nell Nelson](http://nelson.newtfire.org/ChicagoTimes_XML_gender/1888-07-30-ChTimes.xml).  Yes, these two texts are of different genres, therefore they are coded slightly different.  However, they both do not have any overlapping hierarchies and maintain the OHCO layout.  I like to think of OHCO like an outline that you're creating for a text, but as Kirilloff mentions, OHCO is also thought about as a tree.
Although OHCO helps to keep all digital humanists on the similar path of text encoding, as Kirilloff mentions, there is also some problems with OHCO.  One of the major problems with OHCO is that we, as coders, are not allowed to have tangled tags, such as Kirilloff shows us.  it is a slight problem when we have a word that is hyphenated and half of it moved to the next line.  This means that we cannot tag the word as a whole if we are also tagging the lines.  However, in my experience with text encoding, this has never really been a problem with the texts I have coded.

Kirilloff mentions CONCUR, which is an alternative approach to OHCO.  She states that CONCUR allows tangled tags, or overlapping hierarchies.  This, in itself, may preserve how the text is to be read.  However, there are a few ways that you could write XML to avoid the problems of tangled tags, such as using self-closing tags at the end of lines instead of wrapping the lines in `<line>` tags.  (Example: `<word>eng-<line/>ineers</word>`).  Another way to write XML to avoid this problem would to be to use attributes within the element.  (Example: `<line><word type="start" entire="engineers">eng-</word></line><word type="end" entire="engineers">ineers</word>.`)

I can't wait to hear what the rest of you all understand about the piece!

**Comment by mmm202** [comment] 2016-01-10 18:14
I agree that OHCO is great for keeping everything organized and easily understandable. The major problems that arise from OHCO doesn't seem like something that would cause issues a lot. The way that OHCO organizes code overrules the problems that come from it. When overlapping hierarchies arise I see that there is a way to get around it but don't quite understand it yet. Anyone care to explain further?

**Comment by ebeshero** [comment] 2016-01-10 23:18
Hi @mmm202! Here's the problem: Say you're coding something with a really tight structure, like lines of a poem, or paragraphs of a book. Often we want to code those in XML as part of our ordered hierarchy, because it really makes sense to do something like this:

`
<xml>

       <p>Hi! I'm a body paragraph. text text text text text text text text text text text text text text </p>

       <p>And I'm another body paragraph..... </p>

</xml>
`
But then, what if we're reading along in a letter or a book, and trying to code what we see, and the writer has a word break off at the end of a paragraph, and pick up with it at the start of the next one? If we tried to code that following the above organized hierarchy, it makes a problem:

`
<xml>

       <p>Text text text text...He went to the store and spotted someone he thought he knew, and something caused him to retreat with instinctive fear. Could it really be, the very same...? But what was his name? Could it be Jon, whatishis name, Jon...?

</p>

       <p>...Snow! Of course it was. And now we're in another body paragraph..... </p>

</xml>
`
So, say we wanted to code the full name here! The paragraph tags we've applied are getting in the way! Kirilloff suggests a way around this, but she's not happy with it--and it involves the use of self-closing elements: <p/> . How would it work?

**Comment by brookestewart** [comment] 2016-01-11 00:58
Kirilloff discusses how it is left up to the scholar to decide how to interpret and label parts of the text that is being marked up. One example she used is the preservation of the original punctuation while digitally transcribing an author's work. We ran into this issue in the [Emily Dickinson: Fascicle 16] (http://dickinson16.newtfire.org) project last semester. @nlottig94 and I had the task of transcribing Emily Dickinson's poems from her handwritten manuscripts, and it was difficult at times to determine whether a mark was supposed to be a comma or a dash, for example. Kirilloff states that "If the goal of creating a print transcription is to visually reproduce the text, classifications of meaning do not have to be made. In such a case, whether or not the mark at the end of a poem was intended as a period or a comma is irrelevant, it’s shape, color, and size are important. However, in the creation of a digital version of a text, decisions about classification are made even if the focus is on rendering a digital version that is visually similar to the original." 
Our goal was not only to represent the text as accurately as possible to the original, but to study how published versions changed the punctuation and how that changed the meaning. So, it became a question if the changes were made intentionally, to make the poems "more readable", or if that's what the transcriber thought the punctuation really was. 
In transcribing a text, there is going to be a margin for interpretation, which leaves room for inaccuracies as well as personal preference in the coding choices. You can visit our project website (linked above) to read more about how we dealt with these issues.

**Comment by spadafour** [comment] 2016-01-11 01:22
@mmm202 The self-closing tag is sort of like cheating. Here's an example poem:

`<poem>`
`----<line n='1'>I am writing a poem to imple-</line>`
`----<line n='2'>-ment a split word. Simple!</line>`
`</poem>`

Before we continue, here's some quick vocab:
The element `<poem>` *contains* two `<line>` elements. We would call these **children**.
Looking at the element `<line n='1'>`, it is *contained by* the element `<poem>`. We would call this the **parent**.

 
Okay, say we wanted to tag single words (this is what she was doing in the reading). Let's just choose the verbs. For the first two verbs ('am' and 'writing'), it's simple, but the third ('implement') will be *tangled* between lines.

`<poem>`
`----<line n='1'>I <verb n='2'>am</verb> <verb n='3'>writing</verb> a poem to <verb n='4'>imple-</line>`
`----<line n='2'>-ments</verb> a split word. Simple!</line>`
`</poem>`

Here's the same thing, but I'll try to visually show you what 'tangled' means:
`<poem'>`
`----<line n='1'>`
`--------I`
`--------<verb n='1'>am</verb>
`--------<verb n='2'>writing</verb>
`--------a poem to
`--------<verb n='3'>imple-
`----</line>
`----<line n='2'>
`---------ments</verb>
`---------a split word. Simple!
`----</line>
`</poem>`

Here's a question: What is the parent of `<verb n='1'>`? What about `<verb n='2'>`? The answer is easy: `<line n='1'>`. But what is the parent of `<verb n='3'>`? The start tag is within `<line n='1'>`, but the end
tag is within `<line n='2'>`. This is tangled!

The reading suggests the self-closing tag to work around that. This basically means a type of placeholder element, but we will try and use it like a normally-closing element. Let's try that out. First, we have to decide if we want the self-closing tag to come before or after the verb (because it cannot contain text); let's choose after:

`<poem>`
`----<line n='1'>I am<verb n='1'/> writing<verb n='2'/> a poem that imple-</line>`
`----<line n='2'>ments<verb n='3'/> a split word. Simple!</line>`
`</poem>`

So if we were to capture the words that come before the self-closing take `<line/>`, we would get: `am`, `writing`, and `ments`.... not exactly what we're looking for. If we chose to place the tag before the word rather than after, we would then grab only the first half of the word.

With everything that I have worked with so far in this class, I have come across no major issues with the way that this system of hierarchy works; this is maybe because we have constrained all of our projects to function inside of this system. However, once you start considering more unusual types of text, certain types of projects might fall out of the scope of this system.

I hope some of this clears it up for you (or anyone else curious about it).

**Comment by jlm323** [comment] 2016-01-11 02:40
Like @mmm202 mentioned, I agree that OHCO is a great method for keeping things organized. This helps with a reader's ability to make sense of a text if they so wished to look at the markup placed on a given document. 

@brookestewart and @nlottig94 I really liked looking at your Emily Dickinson project so I could actually see how you attempted to make the different versions of the poems distinguishable from one another. It does seem to be somewhat difficult in your case to represent the works as accurately as possible since any changes in punctuation could change the interpretation. 

It also seems like what is chosen to be encoded and what is not chosen to be encoded could present differences in interpretation. Kirilloff pointed out that, "if a reader were to observe that a line of a poem by John Donne had been encoded as an example of 'metaphysicalDeceit,' their interpretation of the line might change..." My question is what should be encoded then in order to augment the reader's understanding of the text without producing some sort of bias? Or is that unavoidable?

**Comment by laurenmcguigan** [comment] 2016-01-11 02:44
# History of XML

According to the author, 
 > SGML was intended to facilitate the sharing and storage of large-project documents in law, government, and industry.9 When SGML was developed it was assumed that the system of formal features described would be **based exclusively on a text’s genre**. SGML was not developed for application in humanities scholarship and the primary concerns driving its creation were practical.
> - Kiriloff

SGML is where XML comes from. I believe that the author is saying that the original use of XML or SGML in the 80s was much more simple than how we use it now. When it was first invented, it was more commonly used to organize documents, whereas now, we use them to discover patterns and organize them into more specific categories. Because of this, categories are left up to the interpretation of the coder so the person reading the document may indirectly make assumption about the text based on the categories in which it was encoded. This is particularly evident is a passage by the author:

> Building off of the relationship between markup and scholar, it becomes clear that the rules and constraints of the markup system used can impact the reader as well. The scholar’s choices of categorization and formalization may impact a reader’s interpretation of the text. For example, if a reader were to observe that a line of a poem by John Donne had been encoded as an example of “metaphysicalDeceit,”7 their interpretation of the line might change in the same way it would from reading a piece of criticism.8 This makes sense, since both the markup process and literary criticism are based on interpretation. However, since the scholar’s acts of interpretation are in part based on the constraints of the markup system, the reader’s perception of the text is indirectly influenced by the markup system.

When doing my own coding,  both on the recipe and the letter, I found that every element and attribute were left up, entirely, to my interpretation. The coding I did may work to suffice the needs of my own research, but may not help another scholar. There are no predefined tag sets for certain elements. Therefore, while you may understand the categories of your own code, others may not. For example:

in HTML, there is a predefined tag for paragraph "< p >" while in XML there is not. But if another person were to use
< p >  to define a new paragraph, but I use 
 < paragraph >     instead I may not understand what the coder was implying. It seems simple, but when you get into more specific tags it would assume it would get more confusing. (sorry I had to use spaces, the page was actually making new paragraphs when I put them in) 

Is this what the author is saying about XML? If so, should XML have a more strict set of predefined tags?

**Comment by laurenmcguigan** [comment] 2016-01-11 03:30
@spadafour I understand what you are saying about overlapping hierarchies, but where I am confused is how you are supposed to fix it. Can you give me another example of the coding? or someone else?

**Comment by laurenmcguigan** [comment] 2016-01-11 03:47
I also have a similar question to @jlm323 . If XML is left up to the interpretation of the coder then why do we use it? Why don't we use HTML, which has predefined tags?

**Comment by ebeshero** [comment] 2016-01-11 04:39
@laurenmcguigan and @jlm323 These are great questions, Lauren! We can use HTML (as we do in our projects) to help present and layout the pages in web browsers, and those predefined tags in HTML are connected with presentation markup: Web browsers respond to a (comparatively) simple set of tags, but they aren't really helpful on their own to track detailed information or mark the kinds of meaningful patterns that XML markup can.

XML *is* something that human beings can write in their own way, but have to work on to make it efficient for computers to "read" systematically, too. As long as the system you come up with works for your research and archiving and studying purposes, it's kind of liberating to be able to "roll your own" ordered hierarchy! But, Lauren, you ask a really smart question that has an answer that came from 1987, even *before* SGML. The Text Encoding Initiative (or TEI) is an international organization that sets standards for encoding cultural documents, historic / literary texts, and it's used around the world as a standardized system for writing XML, so that projects can refer to each other. Thus, a `<p>` element does actually mean a paragraph in the TEI (just as it does in HTML), but there are other things that TEI can do like encode lines of a poem as `<l>` elements, and annotations as `<note>` that are only things HTML can approximate in its presentation/ layout orientation on the page. The TEI provides lots of standards for how to tag names and places and contextual information, too, and offers guidelines on keeping track of bibliographies, and more. You'll hear me talk about the TEI a lot, and we did a sustained unit on it in the Fall DH course because our emphasis was on historical documents and manuscripts then. Also, I'm a pretty active member of the TEI community and I was just elected on the Technical Council last October, which is kind of exciting--my term just started this month! My role is to help with writing and explaining the TEI guidelines and testing new code and discuss coding issues with newcomers--it'll be a bit of work--which speaks to a Very Significant Point you and Kirilloff are making: Even when it comes to international standards, the coding we apply is up to debate and should be something we can explain systematically to other people if we want a project to be something with a good future that we can pass on.

To start learning XML, which is our most important goal in these first couple of weeks of the course, we want you to start thinking about these issues, and realizing the challenge of writing a good hierarchy! You can borrow on the TEI or even use it in your course projects (as our project teams did last year)--but as @spadafour and @RJP43 can tell you, even working with a standard international tag set can raise all kinds of debates!

**Comment by ebeshero** [comment] 2016-01-11 13:45
Also, we'll model a couple of ways to deal with overlapping hierarchies in class today, and we're hoping to bring a guest speaker, Wendell Piez, to show us something of an alternative markup system called LMNL that he has devised fir actually working with overlap! If he's coming it'll be in February.

**Closed** 2016-01-22 14:06 UTC
Labels: discussion
