### ISSUE TITLE
SVG 2

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#245] opened 2016-11-08 22:13 UTC
Okay, I haven't gotten much farther than what we did in class and I am totally lost. I'm not getting any output for the x axis, not sure why. This is my code:

````
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    xmlns="http://www.w3.org/2000/svg">
    
    <xsl:output method="xml" indent="yes"/> 
    
    <xsl:variable name="numChapters" select="count(//chapter)"/>
    <xsl:variable name="xSpacer" select="100"/>
    <xsl:variable name="maxXVAL" select="$numChapters * $xSpacer"/>
    <xsl:variable name="maxSpeeches" select="max(//chapter//count(descendant::q[@sp='alice']))"/>
    <xsl:variable name="ySpacer" select="10"/>
    <xsl:variable name="maxYVAL" select="$maxSpeeches * $ySpacer"/>
    
    <xsl:template match="/">
        <xsl:comment>The total number of chapters is: <xsl:value-of select="$numChapters"/>
            The total length of my X axis is now set to: <xsl:value-of select="$maxXVAL"/>
            The maximum number of Alice'a speeches in any chapter is: <xsl:value-of select="$maxSpeeches"/>
            The total length of my Y axis is now set to: <xsl:value-of select="$maxYVAL"/>
        </xsl:comment>
        
        <svg width="100%" height="100%">
            
            <g transform="translate(50 750)">
                
                <xsl:for-each select="1 to 7">
                    <xsl:variable name="yAxis_HashLocation" select=".*100"/>
                    <xsl:variable name="yAxis_HashName" select=". *10"/>
                    <text x="15" y="-{$yAxis_HashLocation}">
                        speeches
                    </text>
                </xsl:for-each>
                
                <xsl:for-each select="descendant::chapter[@witch]">
                    <xsl:variable name="xAxis_HashLocation" select=".*10"/>
                    <xsl:variable name="xAxis_HashName" select="."/>
                    <text x="-{$xAxis_HashLocation}" y="0">
                        chapter
                    </text>
                </xsl:for-each>
                
            </g>
            
            
        </svg>
    </xsl:template>
````

**Comment by RJP43** [comment] 2016-11-08 22:38
@laurenmcguigan you might start out by pulling in the DHClass-Hub and working from [the more complete class example](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/SVG/Alice/alice_Axes.xsl). We didn't get to everything from the example in class, but I think @ebeshero comments are really helpful in understanding where you want to draw things like your x and y axises. 

After you have a look at that ping back on this issue if you are still lost.

**Comment by setriplette** [comment] 2016-11-08 22:52
I just pulled the recent version and the output has a y axis with values that start at 10 and no X axis. So I think I'm having the same problem as Lauren.

I could also use a hint on what my first step should be for starting the homework from the point we left in class. I came up with an xpath that counts Alice's speeches in a chapter, but it doesn't do each chapter

`count(//chapter[@which='1']//q[@sp='alice'])`

Other than that I've got to admit that I do not know what to do or try.

**Comment by ebeshero** [comment] 2016-11-08 22:54
@setriplette @laurenmcguigan @RJP43 There's definitely an x-axis in my output. If you're viewing it in the browser and you don't see it, try pressing `command -` (command and minus) on your keyboard to minimize the window.

**Comment by ebeshero** [comment] 2016-11-08 22:56
https://www.dropbox.com/s/09o46be4obknjo1/Screenshot%202016-11-08%2017.55.55.png?dl=0

**Comment by ebeshero** [comment] 2016-11-08 22:57
<img width="856" alt="screenshot 2016-11-08 17 55 55" src="https://cloud.githubusercontent.com/assets/4014518/20120897/c35a3380-a5dc-11e6-828b-09aa28c0d5f7.png">

**Comment by RJP43** [comment] 2016-11-08 23:03
@setriplette remember from class we discussed the importance of where you put the count function when trying to count the speeches in each chapter. Your expression is counting that specified chapter with those specific descendants instead of counting the specific speeches. Now also the bigger thing to think about is if you are putting the expression inside of the for each then XSLT is doing the work of walking each chapter so specifying chapters is likely not what you need to do.

**Comment by setriplette** [comment] 2016-11-08 23:29
Ok, I am too dumb to minimize. Got it.

I took Rebecca's comment and got a step further. I tried to make my dots for each chapter, and I was really convinced that this was right, but I am outputting nothing. I fussed with the xpath a bit too and nothing.

```` <xsl:for-each select="chapter">
                    <xsl:variable name="xPos" select="@which * $xSpacer"/>
                    <xsl:variable name="yPos" select="count(.//q[@sp = 'alice'])"/>
                    <circle cx="{$xPos}" cy="{$yPos}" r="5" fill="red"/>
                </xsl:for-each>````

**Comment by ebeshero** [comment] 2016-11-08 23:30
@setriplette @laurenmcguigan @RJP43 With this commit, https://github.com/ebeshero/DHClass-Hub/commit/496ad12ae0282e70969a013a143b0b633fdaee7f, I updated my alice_Axes XSLT file so that the output SVG includes an `@viewBox` attribute to better control how much you can see in the visible browser window. Read about and SVG's viewport and `@viewBox` here on Jacob Jenkov's awesome SVG tutorial ( http://tutorials.jenkov.com/svg/svg-viewport-view-box.html) so you can tinker with this on your own SVGs, to play with how big and small they come out in your browser!

**Comment by laurenmcguigan** [comment] 2016-11-08 23:39
This is what mine looks like and I'm still not getting anything to show up even after I minimize it. it looks like this 

````
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    xmlns="http://www.w3.org/2000/svg">
    
    <xsl:output method="xml" indent="yes"/> 
    
    <xsl:variable name="numChapters" select="count(//chapter)"/>
    <xsl:variable name="xSpacer" select="100"/>
    <xsl:variable name="maxXVAL" select="$numChapters * $xSpacer"/>
    <xsl:variable name="maxSpeeches" select="max(//chapter//count(descendant::q[@sp='alice']))"/>
    <xsl:variable name="ySpacer" select="10"/>
    <xsl:variable name="maxYVAL" select="$maxSpeeches * $ySpacer"/>
    
    <xsl:template match="/">
        <xsl:comment>The total number of chapters is: <xsl:value-of select="$numChapters"/>
            The total length of my X axis is now set to: <xsl:value-of select="$maxXVAL"/>
            The maximum number of Alice'a speeches in any chapter is: <xsl:value-of select="$maxSpeeches"/>
            The total length of my Y axis is now set to: <xsl:value-of select="$maxYVAL"/>
        </xsl:comment>
        
        <svg width="100%" height="100%">
            
            <g transform="translate(50 750)">
                
                <line x1="30" y1="-10" x2="{$maxXVAL + $xSpacer}" y2="-10" stroke="black" stroke-width="1"/>
                
                <line x1="30" y1="-10" x2="30" y2="{-$maxYVAL - 100}" stroke="black" stroke-width="1"/>
                
                <xsl:for-each select="1 to 7">
                    <xsl:variable name="yAxis_HashLocation" select=".*100"/>
                    <xsl:variable name="yAxis_HashName" select=". *10"/>
                    <text x="15" y="{-$yAxis_HashLocation}">
                       <xsl:value-of select="$yAxis_HashName"/>
                    </text>
                    
                    <line x1="30" x2="{$maxXVAL + $xSpacer}" y1="{-$yAxis_HashLocation}" y2="{-$yAxis_HashLocation}" stroke="green" stroke-width=".5" stroke-dasharray="10"/>
                
                </xsl:for-each>
                
                <xsl:for-each select="descendant::chapter">
                    <xsl:variable name="xPos" select="@which * $xSpacer"/>
                    
                    <text x="{$xPos}" y="15" text-anchor="end" transform="rotate(-45 {$xPos}, 15)">
                        Ch. <xsl:value-of select="@which"/>
                    </text>
                    
                </xsl:for-each>
               
                    
                
                
            </g>
            
            
        </svg>
    </xsl:template>
</xsl:stylesheet>

 ````

It is basically a carbon copy of what is under class examples. I also tried to start creating circles but am kind of lost. I know we have to do:
//chapter[@which="1"]//count(q[speaker="alice"]) but where do we put it? In a new `<xsl:for-each>`?  and do we need to create a new circle for each chapter, or do we use some sort of variable to grab them?

**Comment by laurenmcguigan** [comment] 2016-11-09 00:43
Wait I think I got the circles, but I am still having trouble getting output :(

**Comment by ebeshero** [comment] 2016-11-09 00:58
@laurenmcguigan I'm taking look...I bet it's something small. Hang in there!

**Comment by ebeshero** [comment] 2016-11-09 01:03
@laurenmcguigan I am definitely getting output on your code, so I wonder why you are not seeing it?
I ran your XSLT, and I get code in the output window in oXygen. I save it, and reopen the file in a web browser and I see grid lines and axes. All looks good so far. I don't see circles yet. 

Now, why don't you see it? When you run your XSLT, do NOT click on HTML for output. (And don't expect to "see" it in the output panel in oXygen. Save your output and open it in a web browser. Also open it in oXygen to make sure it's well-formed SVG.)

**Comment by ebeshero** [comment] 2016-11-09 01:08
For everyone: save your work, and go to a web browser. In Chrome, you can use File > Open, or use `control + o` (or `command + o` on a Mac).

**Comment by ebeshero** [comment] 2016-11-09 01:19
@setriplette I think I see what's not working in your code. Here's what you posted:

````
 <xsl:for-each select="chapter">
                    <xsl:variable name="xPos" select="@which * $xSpacer"/>
                    <xsl:variable name="yPos" select="count(.//q[@sp = 'alice'])"/>
                    <circle cx="{$xPos}" cy="{$yPos}" r="5" fill="red"/>
                </xsl:for-each>
````

Notice, you don't set yPos as a negative value, AND you don't multiply it by your spacer, so I bet you're getting output, but it's coming out *below* your visible space.

**Comment by setriplette** [comment] 2016-11-09 01:25
I had just figured that out before I read the post. Now I have the dots (except for two, the zero values, which are below my line) more or less where I had expected. Now to draw connecting lines.

**Comment by ebeshero** [comment] 2016-11-09 01:26
Yay! :-D

**Comment by ebeshero** [comment] 2016-11-09 01:29
I'm reviewing my own code. Looks like I revised my axis positions from where I started. Just try replotting your axes, so your X axis runs at "0", not "-10". It makes a lot more sense!

**Comment by ebeshero** [comment] 2016-11-09 01:33
Just pushed revised example, with X axis running at Y="0". :-)

**Comment by setriplette** [comment] 2016-11-09 01:41
Ok, now I need another hint. I made lines, but not the ones I wanted. Then I revised, and here is where I am stuck
`<xsl:for-each select="descendant::chapter">
                    <xsl:variable name="xPos" select="@which * $xSpacer"/>
                    <xsl:variable name="yPos" select="(count(.//q[@sp = 'alice'])) * $ySpacer"/>
                    <line x1="{$xPos}" y1="-{$yPos}" x2="{preceding::$xPos}" y2="-{preceding::$yPos}" stroke="red" stroke-width="3"/>
                </xsl:for-each>`

I know we talked about preceding in class, but maybe not in this situation. In what ballpark should I look for my problem? I'm getting a syntax error that is not allowing the $ after preceding.

**Comment by ebeshero** [comment] 2016-11-09 01:53
@setriplette The issue is with using XPath axes (preceding::), designed to walk the XML tree, to apply to variables which are calculated and aren't on the tree.

**Comment by ebeshero** [comment] 2016-11-09 01:58
@setriplette Your variables defined inside `xsl:for-each` are recalculated every time for-each moves to process a new chapter, and for-each won't "remember" the results of a previous run. So, you need to make a new variable that gets the *preceding* (or following) chapter number (for your x2), and another new variable get the count at the *preceding* (or following) chapter, and use that as the y2 of your line.

**Comment by setriplette** [comment] 2016-11-09 02:20
Here's the one I tried to do for the previous x value. There's still something off in how I'm writing this.

`<xsl:variable name= "precX" select="(preceding::chapter//@which) * $xSpacer"/>`

**Comment by ebeshero** [comment] 2016-11-09 02:26
@setriplette  Here's the issue: You're getting *every* preceding chapter, and you only want *one* preceding chapter, the one next door! So get the *first* one on the preceding axis.

Minor stuff: You don't need the double-slash before @which, but it's probably not causing the problem. You don't need the parentheses either, but it's not really a problem!

**Comment by setriplette** [comment] 2016-11-09 02:37
I tried the parentheses because I was (and still am) getting the error "A sequence of more than one item is not allowed as the first operand of '*'"

Here is what I've got on that variable now

`
<xsl:variable name="precY" select="(preceding::chapter[1]//count(q[@sp = 'alice'])) * $ySpacer"/>`

**Comment by ebeshero** [comment] 2016-11-09 02:45
@setriplette You don't need the parentheses. You stop on a for-each loop on one chapter at a time. When I stop on chapter three, and I look back at the preceding::chapter[1], I get chapter 2. Now, you *will* have a problem if you haven't accounted for the only chapter in _Alice_ that *doesn't have   a preceding:: chapter*. You only want to draw these lines to start from chapters *that have preceding chapters*. You can handle that in an `<xsl:if>`. 

In the version of your post that I saw in my e-mail, you were getting too many counts in your y. You only want *one* count inside an entire chapter, so wrap your whole chapter path in a count().

**Comment by setriplette** [comment] 2016-11-09 02:53
Where would the `xsl:if` go? Inside or outside the for each, inside or outside the variable I'm naming?

**Comment by ebeshero** [comment] 2016-11-09 02:54
Inside the for-each, after you've plotted your dots, and surrounding everything you need to draw those lines.

**Comment by ebeshero** [comment] 2016-11-09 03:10
So, *if* there's a chapter that has a preceding:: chapter, you draw an SVG line from the current chapter to the first preceding chapter.

**Comment by setriplette** [comment] 2016-11-09 03:18
I tried this and am getting no line output anymore, so nothing must pass this if test. I must have to put something else in my if test.

`<xsl:if test="descendant::chapter[preceding::chapter]">`

**Comment by ebeshero** [comment] 2016-11-09 03:19
You're inside a for-each loop that stops on each chapter, so you don't want to go *down* into a descendant chapter that doesn't exist...

**Comment by setriplette** [comment] 2016-11-09 03:21
I tried this

`<xsl:if test="chapter[preceding::chapter]">`

And the same with .//chapter and no output on either.

Am I at least changing the right part?

**Comment by mjb232** [comment] 2016-11-09 03:22
Man, @setriplette , this is great! You keep asking, literally, all the questions I keep running into. Ahhhhh, the beauty of GitHub

**Comment by ebeshero** [comment] 2016-11-09 03:22
Simplify it. You are already on a chapter, so you don't need to say **chapter** again. This is a lot like Schematron...

**Comment by mjb232** [comment] 2016-11-09 03:23
`<xsl:if test="preceding::chapter">`?

**Comment by ebeshero** [comment] 2016-11-09 03:23
YES. You don't need a predicate expression at all. The @test basically sets the filter that you're thinking of as a predicate.

**Comment by mjb232** [comment] 2016-11-09 03:23
Cool, and this wraps around the code I have for my lines?

**Comment by ebeshero** [comment] 2016-11-09 03:24
Yep. Inside the for-each, after you've plotted your dots, and surrounding everything you need to draw those lines.

**Comment by mjb232** [comment] 2016-11-09 03:33
Alrighty, my turn. So i'm outputting lines and such, but I cant get them to land in the right places. This is what I have:
````
            <xsl:variable name="yPos" select="count(.//q[@sp='alice'])*$Yspacer"/>
                    <xsl:variable name="xPos" select="@which * $xSpacer"/>
                    <xsl:variable name="xLine" select="preceding::chapter[1]/@which * $xSpacer"/>
                    <xsl:variable name="yLine"select="preceding::chapter[1]/count(q[@sp='alice'])*$Yspacer"/>

<xsl:if test="preceding::chapter">
                        <line x1="{$xLine}" y1="{-$yLine}" x2="{$xPos}" y2="{-$yPos}" stroke="red" stroke-width="3"/>
                    </xsl:if>
````

**Comment by ebeshero** [comment] 2016-11-09 03:36
@mjb232 Try tucking the variables for preceding:: (the ones you need to draw those lines) inside the xsl:if. I wonder if the parser is having trouble with calculating variables when there *isn't* a preceding:: chapter?

**Comment by mjb232** [comment] 2016-11-09 03:37
Never mind! It the issue was in my 
`<xsl:variable name="yLine"select="preceding::chapter[1]/count(q[@sp='alice'])*$Yspacer"/>`
when I call upon the count for the q element is should look like this:
`count(.//q[@sp='alice'])*$Yspacer` and not `count(q[@sp='alice'])*$Yspacer`

**Comment by ebeshero** [comment] 2016-11-09 03:37
By the way, everyone, you could just as well do this with following::, or following-sibling::, or preceding-sibling:: . And in every case, you need an `<xsl:if>`, because there's only a finite number of chapters.

**Comment by laurenmcguigan** [comment] 2016-11-09 04:22
Got it!

**Comment by ebeshero** [comment] 2016-11-09 04:24
Huzzah!!! :-D Go for the bonus! You can DO it!

**Comment by ahunker** [comment] 2016-11-09 04:55
I can't seem to get my circles to appear. I could use some help. I've looked at the above discussion but can't figure out where I'm going wrong.
```
                <xsl:for-each select="chapter">
                    <xsl:variable name="xPos" select="@which * $xSpacer"/>
                    <xsl:variable name="yPos" select="count(.//q[@sp = 'alice'])"/>
                    <circle cx="{$xPos}" cy="-{$yPos}" r="5" fill="blue"/>
                </xsl:for-each>
```

**Comment by ebeshero** [comment] 2016-11-09 04:56
@ahunker You need to step down into your chapters, if you're inside the template rule that matches on your document node.

**Comment by ahunker** [comment] 2016-11-09 05:01
I'm getting circles now, but my Y isn't working right. Do I need to multiply my count or something because all the circles are below the 10 line?

**Comment by ebeshero** [comment] 2016-11-09 05:03
@ahunker Right: Take a look at how the hashmarks on the Y axis are spaced apart: You want to use the same "spacer" value to multiply your count value, so your plot is scaled to fit the graph.

**Comment by ahunker** [comment] 2016-11-09 05:10
My cirlces are showing up correctly now! Now on to the lines...

**Comment by RJP43** [comment] 2016-12-30 19:11
Closing for Spring 2017 Semester

**Closed by RJP43** 2016-12-30 19:11 UTC
Labels: help wanted
