### ISSUE TITLE
Bad Graphs! (Discussion for Wed. 1/25)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#272] opened 2017-01-23 05:49 UTC
It's much too easy to lie with numbers and graphs on digital humanities projects, and in the digital world generally! We will be posting links here of the good and the bad with graphing and using digital visualizations to share qualitative information on DH projects. 
Please begin by reading [**"A short tour of bad graphs"**](http://people.stat.sfu.ca/~cschwarz/Stat-650/Notes/PDF/ChapterBadgraphs.pdf)  In addition, here is [a set of slides we were showing in class](http://www.slideshare.net/ebbondar/bad-infographics-some-examples ) to illustrate problematic graphs.
Read this carefully, think about the advice given about graphs, and look carefully at the examples and discussion of problematic visualizations of data. 
### Discussion points:
- See if you can understand what's wrong with the examples in the reading, and if you have questions, about examples or advice in the reading, post them here! 
- Each of you in your posts should look on the web for two examples of bad graphs, and tell us what's wrong with them!
- There's no minimum or maximum number of posts: We'd like you to comment on each other's examples, discuss interesting examples from the reading, and locate two examples of your own from the web, just to practice your critical eyes and give this some thought collectively! Let's see what you all come up with.  

(For GitHub practice, try downloading image files of bad graphs, pushing them to the DHClass-Hub Sandbox folder, and linking to them here in the Issues discussion. To make a link to a file, go find it in a new tab and copy its web address. You can just paste the address here. Or try pasting the image into the issue.)

**Comment by Samantha-Mcguigan** [comment] 2017-01-24 01:30
![image](https://cloud.githubusercontent.com/assets/24962247/22230309/cae4f072-e1aa-11e6-950a-4104f58be895.png)

**Comment by Samantha-Mcguigan** [comment] 2017-01-24 02:19
![imrs](https://cloud.githubusercontent.com/assets/24962247/22231445/ad4bfca2-e1b1-11e6-879f-59c0d91de537.jpeg)

**Comment by ebeshero** [comment] 2017-01-24 02:46
@Samantha-Mcguigan Both of these graphs are great examples of how the scale of an axis can alter perspective on an issue, quite dramatically. I tend to agree with you about the first graph--the single decimal place isn't a big deal. The big deal really *is* the way the bars are chopped near the tops, as if 101.7 million were *much less than half* of 108.6 million.

**Comment by bsf15** [comment] 2017-01-24 14:32
I never really noticed before how bad a pie chart can be at efficiently representing data since they are such popular graphs. Like the one graph included in the reading about job security has the one slice representing 6% larger than the slice representing 8% shows a misleading representation of the data. Also, seeing the one pie chart about revenue and expenses by source with an overwhelming amount of data on it really helped prove the point that there are many different graphs to use that can handle particular data sets better. 

Another example they showed that I thought was very tedious to read was the first graph comparing where we donate to diseases that kill us. At first, it looked okay until you simply tried to match up the information to the colored circles. There was too much information for the color coding and as the article said, just labeling the circles would have been more clear. The article made it very clear than simple, easy to read graphs tend to be better than the flashy graphs with lots of unnecessary photos or 3D embellishments.

 One graph that I found online that was bad was this one: 
![bad graph 1](https://cloud.githubusercontent.com/assets/24962232/22251104/96bc31d0-e217-11e6-89ca-22ab48b69b39.jpg)

First of all, I have no idea what the graph is even representing since there is no title. Also, the graph shape itself makes the data distorted if you can even decipher what indicates the slices of the pie chart(I’m assuming it is divided by the yellow and blue area, the yellow and blue area that is slightly faded, the almost white section, the white section, and the bright blue section.). Another thing that jumped out at me after looking at it for awhile was that the 2% slice appeared to be very similar in size as the 8% slice. Perhaps, better text indications and clearer divides of the slices of pie could help this graph, but maybe a different graph style could even work better for this information.


Another bad graph that I found is this one: 
![bad graph 2](https://cloud.githubusercontent.com/assets/24962232/22251114/9e7eba5a-e217-11e6-8d61-eeead6d4dc1f.jpg)

The very obvious issue is the bad representation of the data as the lowest amount (13%) is the highest bar and none of the bar sizes coordinate with the data actually being presented. I was curious if perhaps it was just inverted at first and if the highest bar was intended to represent the lowest amount, but after looking for another second I saw that the 28% bar is nonexistent while the 34% is the second highest bar on the graph. The bars alone without the numbers convey totally different information from what you would immediately interpret from looking at a bar graph like that has no further labelling.

**Comment by jonhoranic** [comment] 2017-01-25 02:56
Charts that attempt to use 3D graphics seem to fall flat nearly 99.9% (not actual figures) of the time. Take for example this eyesore I found browsing around google images.

![image](https://cloud.githubusercontent.com/assets/21690665/22275616/ed5d63d8-e27b-11e6-90d7-5c39632f71c7.png)
This is probably an intentionally bad graph for example purposes, but if it is a real attempt at making a graph to represent data of some sort the author should give up graphing altogether.

So what is wrong with this graph?
1. The overlap of the bars make it unreadable, they could have been ordered so the smaller ones would would be in front of the taller bars, but the data overall would still make this look sloppy.
2. Each bar has a number label "on" it, but they are all off set so there is no way of telling which bar a tag goes to. The labels do not even line up with the numbers on the Y axis.
3. Why have a color key if they are already marked (although poorly) on the Z axis? It is redundant.
4. MISSING. AXIS. LABELS!!! The lack of these are infuriating, what on earth are these numbers indicating? Who are these people and why are they relevant? What do these cardinal directions indicate? This lack if information makes the graph pointless
5. No title or description adds on to point number four, what does this graph do? Where is this information for?

This could easily be fixed by making it a 2D stacked bar graph, keeping the colors and the key and adding proper titles, subtitles, descriptions, and labels.

**Comment by jonhoranic** [comment] 2017-01-25 03:18
Though this might not be completely applicable for discussing bad graphs, I did find this while looking around for examples.

![image](https://cloud.githubusercontent.com/assets/21690665/22276573/95b1924c-e282-11e6-905b-d34f7c740250.png)
 I'd say the problem with that graph is self explanatory in this comic!

This is from a site by the interesting name of [xkcd ](https://xkcd.com/). If you have not heard of it, xkcd is a wonderfully nerdy and minimalist webcomic that sometimes has some really interesting graphs and charts mixed in with his posts. I also recommend that when browsing to click on the "[What If?](http://what-if.xkcd.com/)" section, where the author takes the time to do calculations and research to try to solve absurd fan made questions. Like [how much spit would it take to fill and Olympic size swimming pool](https://what-if.xkcd.com/144/).

**Comment by ajnewton1** [comment] 2017-01-25 03:46
![pov](https://cloud.githubusercontent.com/assets/24962219/22276899/0865ee8a-e285-11e6-8713-9a719464b6b7.jpg)
This photo shows the way the bar graph was actually demonstrated when it was first introduced on the right, and on the left is what it should actually read. It looks like this example was made by a New York Yankee fan trying to display that his team is a lot better than the Red Sox. By the looks of the 'Wrong' graph, he did an excellent job at doing just that as it looks like the Yankees have won 3 or 4 times more than the Red Sox and that is not at all what the graph should read.

![97320630005350f1](https://cloud.githubusercontent.com/assets/24962219/22276980/e2c51e7a-e285-11e6-885f-9043dd150aa7.jpg)
First of all, whaaaaaaat is going on in this bar graph. This sorta looks like a 2D version of the example @jonhoranic gave us although this one has axis labels and a title... which doesn't make it any better. These numbers are just so jumbled up its almost impossible to read. Actually, the more you look at it it basically is impossible to read.

The pie graph that @bsf15 shared with us is one of the worst I have ever seen. From what I am understanding from that graph, it looks like the whiteish clearish color demonstrates the size of the section (which is still hard to read) and the colors of the graph are just there to mess everything up. All together a terrible choice of graphing by that person.

**Comment by ahunker** [comment] 2017-01-25 05:41
This first [graph](https://solomonmessing.files.wordpress.com/2012/01/primarypie15.png) is rather ineffective visually. I'm not sure what is actually being shown because there are no percentages/data or explanation other than a very vague title of 'New Hampshire Primary 2012'. The other big issue with this graph is that it is badly formatted. I can't read a lot of the names presented because the amount of data for each name is incredibly small. I can't even see a difference on the chart itself at times as the data decreases, it just looks like a giant black line. 

 This second [graph](http://www.statisticshowto.com/wp-content/uploads/2014/01/pie-chart-misleading.png) just makes me laugh. It has a clear title, percentages, labels, and is visually readable, but is just wrong. Anyone who has attended a basic math class or owns a calculator knows that 70%, 63%, and 60% don't equal 100% when added together. The other thing is I don't know who is backing each of the candidates. It just says that 63% back Huckabee, but who is part of that 63%? 

 @ajnewton1 If I didn't already have a headache, I'm sure I would have gotten one while looking at your second graph.

**Comment by Samantha-Mcguigan** [comment] 2017-01-25 06:17
@bsf15 I was looking at your bar graph and it seems to have similar problems as the one I posted with accurately representing data with the heights of the bars. They also both fail to label the y-axis. I think the problem with misrepresenting the heights of the bars on the graphs stems from not labeling the y-axis. It would be easier for someone not to notice that the bars do not correctly represent the data when there is nothing to compare it to. It is misleading to the reader. It is just unethical graph making.

**Closed** 2017-03-17 11:40 UTC
Labels: discussion
