### ISSUE TITLE
xslt 5 toc outputting whole text of poems

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#237] opened 2016-10-30 19:08 UTC
Hi all! I'm at the table of contents step on the assignment and I've made my document node match and attempted to style it also. I'm outputting stuff in the toc but unfortunately it is the whole poem. Can anyone help me see why?

In my document node section I have
`<ul><xsl:apply-templates select="$dickinsonColl//body" mode="toc"/></ul>`

In the part where I style things I have
`<xsl:template match="$dickinsonColl//body//title" mode="toc"><li><xsl:apply-templates/></li></xsl:template>`

and

`<xsl:template match="$dickinsonColl//body//lg[1]//l[1]" mode="toc"><xsl:apply-templates/></xsl:template>`

What am I not getting? My attempt here was to in the first match output the titles of the poems wrapped in element `<li>`.vMy goal on the second match was to make it output the text of line 1 of each poem set. I checked my xpath and it did indeed get me onto the first line of the first line group. I tried adding in a path step to text() at one point and got an error from xslt saying that text in the child axis will never match on anything.

**Comment by ebeshero** [comment] 2016-10-30 19:58
@setriplette I think you are outputting the entire poems because of the `<xsl:apply-templates>` in your document node, where you say:
`<ul><xsl:apply-templates select="$dickinsonColl//body" mode="toc"/></ul>`

You've written your template matches in the "toc" mode on descendants of body, but because there's no template rule matching specifically ON $dickinsonColl//body, you're getting the default to fire, which is spitting out the text. 

My recommendation is to rewrite your template match, so @match="$dickinsonColl//body" in the toc mode, and then select what you want to output inside that template match on the body of each poem. Does that make sense?

**Comment by ebeshero** [comment] 2016-10-30 20:09
By the way, you can trust the XPath pattern-matching to understand what to do if you write:

````
<xsl:template match="body">
    <HTMLwrapper>
    <HTMLtag><xsl:apply-templates select="descendant::path/down/toWhatYouWant"/>  </HTMLtag>
     <HTMLtag2><xsl:apply-templates select="descendant::path/into/theOtherThingYouWant"/>     </HTMLtag2>
    </HTMLwrapper>
</xsl:template>
````

**Comment by setriplette** [comment] 2016-10-30 20:41
Ok, I changed my document node match to

`<ul><xsl:apply-templates select="$dickinsonColl//body//title" mode="toc"/></ul>`

Which output the titles of the poems nicely. I'm still not getting my thinking around picking up the first lines in that same rule, since it's a bit different path--title and lg are siblings

**Comment by setriplette** [comment] 2016-10-30 20:45
And I tried something different...

Now I have two toc lists, one of titles and one of first lines. 

Here's in my document node (I'm liking this)
`<ul><xsl:apply-templates select="$dickinsonColl//body//title" mode="toc"/><ul><xsl:apply-templates select="$dickinsonColl//body//lg[1]//l[1]" mode="toc"/></ul></ul>`

And here's what I think is the new problem

`<xsl:template match="$dickinsonColl//body//title" mode="toc"><li><xsl:apply-templates/></li></xsl:template>
    <xsl:template match="$dickinsonColl//body//lg[1]//l[1]" mode="toc"><li><xsl:apply-templates/></li></xsl:template>`

I want a list of first lines within that list of titles, right?

**Comment by setriplette** [comment] 2016-10-30 20:54
I did reread the comment and tried outputting just the body in my document node mode = toc. When I did that, no matter what I matched below, the whole poem output.

**Comment by setriplette** [comment] 2016-10-30 21:00
I also take the point about the simpler matches below the end of html and they did work.

**Comment by setriplette** [comment] 2016-10-30 21:06
Ok, I figured it out. Wow, talk about a complicated match! Which maybe indicates that I'm still doing it wrong, but desired output achieved.

**Comment by RJP43** [comment] 2016-10-30 21:12
Ahhh okay, I was just getting around to trying to comment on this issue... but if you are getting the correct output ... kudos! Make sure you save the output file and reopen it to check that it is well-formed HTML; sometimes it is difficult to see in the output window.

**Comment by setriplette** [comment] 2016-10-30 21:16
It was SO NOT well-formed xml. Red vampire oxygen. I just fixed that though.

**Comment by laurenmcguigan** [comment] 2016-10-31 03:01
Okay I am also having an issue. For some reason, my output is reversing the TOC and the body underneath and then not using any of the html I specified for it. My xslt looks like this 

````
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">

    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    <xsl:variable name="dickinsonColl" select="collection('Dickinson')"/>

    <xsl:template match="/">
        <html>
            <head>
                <title>Emily Dickinson’s Fascicle 16</title>
            </head>
            <body>
                <h1>Emily Dickinson’s Fascicle 16</h1>
                <h2>Table of Contents</h2>
                <ul>
                    <xsl:apply-templates select="$dickinsonColl//body" mode="toc"/>
                </ul>
                <hr/>
                <div id="main">
                    <xsl:apply-templates select="$dickinsonColl//body"/>
                    <xsl:apply-templates select="/head/title"/>
                </div>
            </body>
        </html>
    </xsl:template>
    
    <xsl:template match="body">
        <li><xsl:apply-templates select="descendant::title" mode="toc"/></li>
    </xsl:template>
    
    <xsl:template match="title">
        <h2>
            <xsl:apply-templates/>
        </h2>
    </xsl:template>
````

**Comment by laurenmcguigan** [comment] 2016-10-31 03:30
Everything was fine until I tried to make the TOC is it because my template selects are the same for both, because I tried changing them and it just made it worse

**Comment by laurenmcguigan** [comment] 2016-10-31 03:33
it is currently putting the ul tag around all the body text and the div tag around my toc

**Comment by laurenmcguigan** [comment] 2016-10-31 03:44
So I think it is something with my TOC because when I take out all the xslt for the main part, I am still outputting all the text in the toc. However when I take out the xslt for the TOC everything seems to be working just fine. So for some reason it seems like my xslt for the TOC is relying on something in my xslt for the main part, but I'm not sure what. I looked over everything Dr.B wrote for Professor Triplette, and I thought I was doing it correctly, but I guess not.  @ebeshero @RJP43

**Comment by mjb232** [comment] 2016-10-31 05:15
Alright, my turn. So I've gotten everything to output correctly, minus the actual poems.  I cant get each individual instance of `lg` to output as a `p` element. If I can figure out how to do that, the rest is easy but i caaaaaaaaaaaant, so someone help me pleaseeeeeeee.

````
    <xsl:template match="$poems//body">
        <h4><xsl:apply-templates select="head"/></h4>
        <xsl:apply-templates select="descendant::lg"/>
    </xsl:template>

    <xsl:template match="descendant::lg">
        <xsl:apply-templates select="descendant::l"/><br/>
</xsl:template>

````

**Comment by mjb232** [comment] 2016-10-31 05:34
@laurenmcguigan  Alright, so I think your issue lies in how you are defining you modals. So your 
````
<body>
                <h1>Emily Dickinson’s Fascicle 16</h1>
                <h2>Table of Contents</h2>
                <ul>
                    <xsl:apply-templates select="$dickinsonColl//body" mode="toc"/>
                </ul>
                <hr/>
                <div id="main">
                    <xsl:apply-templates select="$dickinsonColl//body"/>
                    <xsl:apply-templates select="/head/title"/>
                </div>
            </body>
````
Is correct, now the issue is that the line:
 ` <xsl:apply-templates select="$dickinsonColl//body" mode="toc"/>`
should have it's own `<xsl:template match="$dickinsonColl//body" mode="to">`

**Comment by mjb232** [comment] 2016-10-31 05:39
As you have it now, your `mode="toc"` isn't actually defined. For every `mode` you make you should have a `xsl:template` to define.

**Comment by laurenmcguigan** [comment] 2016-10-31 05:58
@mjb232 Where do I put the new match?

**Comment by laurenmcguigan** [comment] 2016-10-31 06:00
@mjb232 nevermind!

**Comment by mjb232** [comment] 2016-10-31 06:01
The new match should look like this 
`<xsl:template match="$dickinsonColl//body" mode="toc"></xsl:template>`
and should replace your
````
<xsl:template match="body">
        <li><xsl:apply-templates select="descendant::title" mode="toc"/></li>
    </xsl:template>
```
Then within the new template you just made, call upon the various elements you need to style

**Comment by mjb232** [comment] 2016-10-31 06:01
Oh, wait, guess you didnt need that. Well, there you go anyways haha

**Comment by mjb232** [comment] 2016-10-31 06:03
Anything else I can assist with?

**Comment by RJP43** [comment] 2016-12-30 19:14
Closing for Spring 2017 Semester

**Closed by RJP43** 2016-12-30 19:14 UTC
