### ISSUE TITLE
FileZilla almost working...

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#441] opened 2018-02-03 19:16 UTC
@ebeshero @jonhoranic @alexfell06 @MarkTheShark01 @dorothealint @Pomilui @garrettjoiner @quantum-satire

  Hey, all.  I was able to set up FileZilla earlier today and I made a new key on my home PC.  However, I'm getting these errors in the FileZilla command screen:  

Status:	Connecting to firebellies.newtfire.org...
Response:	fzSftp started, protocol_version=8
Command:	keyfile "C:\Users\Nick\.ssh\id_rsa.ppk"
Command:	open "pomilui@firebellies.newtfire.org" 22
Command:	Trust new Hostkey: Once
Command:	Pass: 
Error:	Authentication failed.
Error:	Critical error: Could not connect to server

  Any ideas on what I need to do?  Thanks.

 - Nick

**Comment by ebeshero** [comment] 2018-02-03 19:54
@Pomilui I think I know what the problem is: You set up access with a different SSH key yesterday, which is good. But now with a new key, you might not have succeeded in getting the new public key up on the server. I am away from my computer right now, but what I would check is whether we can see two public keys on the server, or just one.

You can see this yourself I think. See if you can use your shell to run 
`ssh pomilui@firebellies.newtfire.org` . You should I think still be prompted for the simple password I set for you, which will let you get in and look in your directory. If you can get in, look at everything (including hidden directories) with:
`ls -lisa`

Look inside the .ssh directory (review your command line navigation to change directories and list out files) and see whether you have two files inside with .pub extension or just one.

**Comment by Pomilui** [comment] 2018-02-03 20:40
I got in and cd'd into .ssh and saw only one file with .pub 

`$ ls -lisa
total 28
786445 4 drwxr-xr-x  4 pomilui users 4096 Feb  2 11:04 .
     2 4 drwxr-xr-x 48 root    root  4096 Feb  2 10:58 ..
786447 4 -rw-r--r--  1 pomilui users  220 Feb  2 01:59 .bash_logout
786448 4 -rw-r--r--  1 pomilui users 3515 Feb  2 01:59 .bashrc
786446 4 -rw-r--r--  1 pomilui users  675 Feb  2 01:59 .profile
786449 4 drwxr-xr-x  2 pomilui root  4096 Feb  2 02:21 public_html
786450 4 drwx------  2 pomilui users 4096 Feb  2 11:14 .ssh
$ cd .ssh
$ ls
authorized_keys  id_rsa  id_rsa.pub  known_hosts`

**Comment by ebeshero** [comment] 2018-02-03 21:33
@Pomilui Looks like you have two files there, though. And the one without .pub should NOT be there. I would delete that one, delete the keys on your local computer and start over(!)

**Comment by ebeshero** [comment] 2018-02-03 21:44
@Pomilui Since you are making a separate set of keys to authenticate from home, let’s try adding something to the front of the new set of the new keyfiles, like home-id_rsa, etc. make sure the names match, and that you only transfer the public key to the server. We’ll figure this out!

**Comment by ebeshero** [comment] 2018-02-04 01:56
@Pomilui I'm back home now--How did you fare with the new set of keys?

**Comment by Pomilui** [comment] 2018-02-04 16:41
I deleted the file without the .pub ending in the /users.../.ssh folder and tried connecting again, but no dice.  I'm unsure on how to delete the keys on this local computer and start over.  Should I do a re-install of Filezilla or delete the keys in GitBash?

**Comment by ebeshero** [comment] 2018-02-04 18:26
@Pomilui You don't need to re-install Filezilla.  What needs to happen is that you generate a key-pair on your home computer, and place the new public key on the remote server.  It sounds like you did that on your home computer, but weren't able to transfer the new public key over such that you could authenticate there. I think that's because you *already* have a public key of the same filename on the remote server--and that one is in place for you to authenticate from the campus computer labs. You can leave that public key (on the server) alone--it's working at school. 

But on your home computer: Try browsing to the .ssh directory and take a look there: do you see a pair of key files, and one with a .pub extension? If so, that's good. A simple solution, if you can see a pair of keys on your local computer will be to rename them so they are distinct from the key names you're using for the computer labs. You can rename your files in the GitBash shell with the mv command like this:
```
mv id_rsa home_id_rsa
mv id_rsa.pub home_id_rsa.pub
```
Or you can rename them in your File Explorer--whatever you prefer. Try to transfer the public key to the server. Then with Filezilla, locate the private key, and see if that works.

**Comment by ebeshero** [comment] 2018-02-05 02:49
@Pomilui Did you get this working? (hopeful...)

**Comment by Pomilui** [comment] 2018-02-05 03:33
@ebeshero trying again...

**Comment by Pomilui** [comment] 2018-02-05 03:56
@ebeshero tried this as well:   $ ssh-copy-id -i pomiluihome_id_rsa.pub pomilui@firebellies.newtfire.org

/usr/bin/ssh-copy-id: ERROR: failed to open ID file 'pomiluihome_id_rsa.pub': No such file

Is this what my .ssh folder should look like? 

<img width="566" alt="keys" src="https://user-images.githubusercontent.com/35349892/35787761-7b89bfe2-0a28-11e8-8963-e0ce939f1ab4.PNG">

**Comment by quantum-satire** [comment] 2018-02-05 04:00
@Pomilui It looks like, according to the warning note in your previous comment, you're trying to create a key that already exists on the server...

**Comment by quantum-satire** [comment] 2018-02-05 04:01
@Pomilui When you say you have two keys in your .ssh folder, does one of them have .pub at the end and the other does not?

**Comment by ebeshero** [comment] 2018-02-05 04:58
@Pomilui I’m back...Your .ssh directory on your local computer looks right, and you want to be using that exact file name to transfer to the server. Let me take a look at what’s on the server...

**Comment by ebeshero** [comment] 2018-02-05 05:16
@Pomilui On the server, I don't see any sign that the second .pub key has transferred. You want to be really careful to get the right filename here. On your local computer if you're sticking with home_id_rsa.pub, that is exactly the filename to transfer. (And yes, in your File Explorer it will appear to be a Microsoft publisher file b/c of that .pub extension--that's not a problem--just a silly GUI misinterpretation.) One other option is, if you copied your keys you made on the lab machine, you could transfer them in to your local computer, and just associate FileZilla with the local (private) id_rsa key--it should match the key currently on the server.

**Comment by ebeshero** [comment] 2018-02-05 05:17
@Pomilui I also half wonder if your system actually is working...Try closing FileZilla and reopen it...does it connect?

**Comment by Pomilui** [comment] 2018-02-09 01:43
@ebeshero @jonhoranic @quantum-satire   Hey, all.  I'm attempting the home work and connecting to the server through FileZilla again tonight.  I did not copy my key from my lab machine, but I did copy all of the text in the GitBash from that day.  I will try copying my home key to the server in gitBash as well.

**Comment by Pomilui** [comment] 2018-02-09 01:59
I'm IN!!  Please make sure that I uploaded the right key.  
![goldeneye_borris](https://user-images.githubusercontent.com/35349892/36007964-d934a514-0d3c-11e8-9dd8-fa34c918903b.gif)

**Comment by ebeshero** [comment] 2018-02-09 02:31
@Pomilui It looks okay to me from here, and if you're getting in and the connection is working, you're in great shape! Huzzah!

**Closed** 2018-03-21 11:46 UTC
Labels: HELP needed
