### ISSUE TITLE
Why is my network graph so ugly?

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#465] opened 2018-03-06 20:06 UTC
I adapted the decameron people example (I think) for my Lope collection, I got a list of tab separated values (though I could not view output on the web, I could open the file in exist db and copy-paste), and then I opened a text file in oxygen and saved it as a .tsv. I opened the thing in cytoscape and wow, large blue blot. What am I missing? I think I need to bind some edges together but no idea how. Also--did I miss my distinct values somehow?

[triplette_lopePeeps_existdb.txt](https://github.com/ebeshero/DHClass-Hub/files/1786542/triplette_lopePeeps_existdb.txt)

[lopePersons_tab_separated.txt](https://github.com/ebeshero/DHClass-Hub/files/1786545/lopePersons_tab_separated.txt)

**Comment by ebeshero** [comment] 2018-03-07 14:53
@setriplette I am looking at your XQuery and output, and the output looks to me as if yes, you are catching distinct values for the first set of of names, and yes, for those connected to them up in the text of the entire plays. Some of the nodes are the same, because some have punctuation (like a comma) at the end or some other weirdness in the encoding that you may want to smooth out. But there is something that looks funny to me in your XQuery—am I missing something, or is the “else if” statement below a duplicate of the “If” statement above it?

```
let $peers:= 
    if ($lopePeople[. = $edp]/ancestor::text) 
        then distinct-values($lopePeople[. = $edp]/ancestor::text//persName[not(. = $edp)])
   else if ($lopePeople[. = $edp]/ancestor::text) 
        then distinct-values($lopePeople[. = $edp]/ancestor::text//persName[not(. = $edp)])
   else distinct-values($lopePeople[. = $edp]/ancestor::text//persName[not(. = $edp)])
```

Both seem to be just checking if there is a `<text>` element up above on the ancestor axis. I wonder if you want a different condition, or you just don’t need that second condition?

Now, importing your data into Cytoscape is *always* going to produce an ugly blob or something that looks like the Borg at first. We need to give it some shape and organize it—and we are saving that stage of work for after Spring Break...That said, I will try opening your TSV in Cytoscape and see what I can see!

**Closed** 2018-08-26 20:42 UTC
