### ISSUE TITLE
XLST Exercise 1 ~ replacing <l> with <lb/>

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#378] opened 2017-10-18 18:06 UTC
I think I'm close with this, but I'm not quite getting the output that I need. 

I'm working with this question on the exercise right now:

> Now, write the template rule that will match only on <l> elements that are children of <head> elements. And see if you can figure out how to replace these by positioning the self-closing line-break element <lb/>, positioned in the correct spot in relation to <xsl:apply-templates/> so that the <lb/> sits at the end of a line.

Here is what I tried:
```
 <xsl:template match="head/l">
     <l></l>
        <xsl:apply-templates/>
      <lb/>
    </xsl:template>
```
This gave me an output that looks like this, with the closing tag of <l/> still at the beginning of the line:
```
 <head>
                     <l/>CHAP. I.<lb/>
                     <l/>Departure - Passage from <placeName instant="false" full="yes">Plymouth</placeName> to
                           <placeName instant="false" full="yes">Madeira</placeName> - Description of that Island.<lb/>
                  </head>
```
I don't know why it keeps leaving the <l/> at the beginning of the line.

**Comment by ghbondar** [comment] 2017-10-18 18:20
@kes213 Notice that your line-elements in your template have no content. You might want to move the closing-tag to after you apply the template, around where your LB-tag is.

**Comment by ebeshero** [comment] 2017-10-18 19:01
@kes213 @ghbondar Well, the problem is also that we want to get rid of those `<l>` elements in the first place--because they're not good TEI markup. (`<l>` is for lines of poetry, strictly in TEI.) So we want to get rid of them entirely. Kaylee, your code is putting them back so they're coming out as a self-closing element...

**Comment by ebeshero** [comment] 2017-10-18 19:02
@kes213 ...So what would happen if you just didn't represent those tags at all?

**Comment by kes213** [comment] 2017-10-18 19:08
Oh, okay, I see. I got it to work. Thank you!

**Comment by pab124** [comment] 2017-10-20 02:00
@ebeshero @ghbondar I'm on the last problem for this assignment, dealing with the AVT's and I started to have a little trouble. I'm not quite sure how to capture the `div` elements for the Books and Chapters by themselves, that is, I'm unsure of how to include the `div` elements that are marking the books.

**Comment by ebeshero** [comment] 2017-10-20 02:34
Hi @pab124 : You want to write a template rule that matches on the divs that are books, first of all. That's just a pattern, but it's okay to indicate a predicate expression. (So while you wouldn't "walk down the tree" from the document node in an `<xsl:template match="someplace">` expression, you may still set a predicate filter inside it: `<xsl:template match="someplace[@type='likeSo']">`. Be careful to nest your quotation marks: single quotes inside your pattern-match, so the `@match` attribute takes double quotes. 

Does that help? If not, post some code here in markdown and we'll see if we can help.

**Comment by pab124** [comment] 2017-10-20 02:54
@ebeshero That was very helpful, yes. I was using predicates before, but the @type seemed to completely slip my mind. Thank you for the help. One other question I had though, regarding these AVTs, was about adding in the attribute values initially. When an attribute is added through the transformation process, does it replace/eliminate pre-existing attributes associated with the element?

**Comment by ebeshero** [comment] 2017-10-20 03:14
@pab124 That is a good and important observation about what happens to element and attribute nodes when they are processed by an XSLT template rule: As you have noticed, the attributes (as well as the element tags) are discarded as a template rule **consumes** the contents of the matched element. If you write nothing at all inside the ‘xsl:template‘ rule, it will *suppress* the node entirely. If you simply set ‘xsl:apply-templates‘ inside, with nothing else, it will output the text node and search for additional template rules to process anything deeper down the tree, but the *current* element wrapper will be lost. You would need to reconstruct if you want to keep its original attributes, and you’d do that with an AVT as well, just reproducing the value of the current match node’s attribute. Give it a try and see how it works!

**Closed** 2017-11-29 13:13 UTC
Labels: HELP needed
